services:
  api:
    build: .
    container_name: olist_recommender_api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models

  streamlit:
    build: .
    container_name: olist_streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./front:/app/front          # O código do painel
      - ./src:/app/src              # Os scripts e utilitários
      - ./data:/app/data            # <-- A PONTE PARA O SEU PARQUET!
      - ./artifacts:/app/artifacts  # <-- A PONTE PARA OS CSVS DOS BASELINES!
      - ./models:/app/models        # <-- A PONTE PARA OS PESOS DO MODELO!
    command: streamlit run front/app_vis.py
    depends_on:
      - api

      